# Generated by Django 5.2.16 on 2026-07-22 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignoVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GLUCOSA', 'Glucosa'), ('SPO2', 'SpO2'), ('TEMPERATURA', 'Temperatura'), ('PRESION', 'Presion arterial')], max_length=15)),
                ('valor', models.FloatField(blank=True, help_text='Para presion usar sistolica/diastolica', null=True)),
                ('valor_sistolica', models.FloatField(blank=True, null=True)),
                ('valor_diastolica', models.FloatField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=15)),
                ('registrado_en', models.DateTimeField()),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('OFFLINE', 'Offline (sincronizado)')], default='MANUAL', max_length=10)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signos', to='appointments.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos', to='patients.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registrado_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_id', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('capturado_en', models.DateTimeField()),
                ('sincronizado', models.BooleanField(default=False)),
                ('sincronizado_en', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_offline', to='patients.paciente')),
                ('signo_vital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_origen', to='clinical.signovital')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('CRITICO', 'Critico')], max_length=10)),
                ('mensaje', models.CharField(max_length=300)),
                ('atendida', models.BooleanField(default=False)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('signo_vital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='clinical.signovital')),
            ],
            options={
                'ordering': ['-generada_en'],
            },
        ),
        migrations.CreateModel(
            name='RangoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_signo', models.CharField(choices=[('GLUCOSA', 'Glucosa'), ('SPO2', 'SpO2'), ('TEMPERATURA', 'Temperatura'), ('PRESION', 'Presion arterial')], max_length=15)),
                ('valor_min', models.FloatField()),
                ('valor_max', models.FloatField()),
                ('valor_min_critico', models.FloatField(blank=True, null=True)),
                ('valor_max_critico', models.FloatField(blank=True, null=True)),
                ('unidad', models.CharField(max_length=15)),
                ('condicion_cronica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='patients.condicioncronica')),
            ],
            options={
                'unique_together': {('tipo_signo', 'condicion_cronica')},
            },
        ),
    ]
