# Generated by Django 5.2.16 on 2026-07-22 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=12)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=6)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('centro_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_entrantes', to='accounts.centrosalud')),
                ('centro_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_salientes', to='accounts.centrosalud')),
                ('especialidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_recibidas', to='accounts.especialidad')),
                ('especialista_destino', models.ForeignKey(blank=True, limit_choices_to={'rol': 'MEDICO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('medico_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='patients.paciente')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoDerivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='derivaciones/')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('derivacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='referrals.derivacion')),
            ],
        ),
    ]
