# Generated by Django 5.2.16 on 2026-07-22 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_cita_min', models.PositiveSmallIntegerField(default=30)),
                ('activo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(limit_choices_to={'rol': 'MEDICO'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['medico', 'dia_semana', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('medico', 'dia_semana', 'hora_inicio'), name='uniq_horario_inicio')],
            },
        ),
    ]
