# Generated by Django 5.2.16 on 2026-07-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(db_index=True, max_length=150)),
                ('accion', models.CharField(max_length=10)),
                ('modelo_afectado', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detalle', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
