# Generated by Django 5.2.16 on 2026-07-22 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionCronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(help_text='Ej. DIABETES, HIPERTENSION, EPOC', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100)),
                ('centro_salud_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='accounts.centrosalud')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PacienteCondicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diagnostico', models.DateField()),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.condicioncronica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_set', to='patients.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'condicion')},
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='condiciones',
            field=models.ManyToManyField(related_name='pacientes', through='patients.PacienteCondicion', to='patients.condicioncronica'),
        ),
    ]
