# Generated by Django 5.2.15 on 2026-07-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="condicioncronica",
            options={"ordering": ["nombre"]},
        ),
    ]
