# Generated by Django 5.2.16 on 2026-07-22 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_legacy_id', models.CharField(max_length=50)),
                ('datos_csv', models.JSONField()),
                ('migrado_en', models.DateTimeField(auto_now_add=True)),
                ('validado', models.BooleanField(default=False)),
                ('paciente_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy', to='patients.paciente')),
            ],
            options={
                'ordering': ['-migrado_en'],
            },
        ),
    ]
