# Generated by Django 5.2.16 on 2026-07-22 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_simulada', models.CharField(editable=False, max_length=64)),
                ('codigo_verificacion', models.CharField(editable=False, max_length=12, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('vigente_hasta', models.DateTimeField()),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescripciones', to='appointments.cita')),
                ('medico', models.ForeignKey(limit_choices_to={'rol': 'MEDICO'}, on_delete=django.db.models.deletion.PROTECT, related_name='prescripciones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='patients.paciente')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetallePrescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=150)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion_dias', models.PositiveSmallIntegerField()),
                ('prescripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='prescriptions.prescripcion')),
            ],
        ),
    ]
